In [1]:
import numpy as np
import pandas as pd

### SOAL 1

In [4]:
arr = np.random.randint(0,201,81)
arr

array([ 58,  29, 130,  68, 127,  58,  31, 192,  88,  45,  98, 182, 132,
        37, 178, 118, 150, 122,  90, 195, 108,  48, 177,  87,  58,  44,
        38, 105, 138,  58, 100,   2,  48, 107,  11, 160, 133,  38,  36,
       112,  93,   5, 167,  52, 172,   8, 124, 123,  31, 139,  21,  47,
        65, 118,  99, 144,  85, 164,  95,  52,  53, 113, 185,  17,  17,
       150, 103, 196,  58,  56,  11, 151,  98,  71, 148,  81,  31,  68,
        34, 142,  27])

In [28]:
v1 = np.random.randint(0,81,1)
v2 = np.random.randint(0,81,1)
v3 = np.random.randint(0,81,1)
v4 = np.random.randint(0,81,1)
v5 = np.random.randint(0,81,1)
v6 = np.random.randint(0,81,1)
v7 = np.random.randint(0,81,1)
v8 = np.random.randint(0,81,1)
v9 = np.random.randint(0,81,1)
v10 = np.random.randint(0,81,1)
v11 = np.random.randint(0,81,1)
v12 = np.random.randint(0,81,1)
v13 = np.random.randint(0,81,1)
v14 = np.random.randint(0,81,1)
v15 = np.random.randint(0,81,1)
v16 = np.random.randint(0,81,1)

In [29]:
arr2 = np.array([arr[v1], arr[v2], arr[v3], arr[v4], arr[v5], arr[v6], arr[v7], arr[v8], arr[v9], arr[v10], arr[v11], arr[v12], arr[v13], arr[v14], arr[v15], arr[v16]]).reshape(4,4)
arr2

array([[118, 105,  56, 132],
       [  2,  21, 148, 150],
       [ 48,  90,  98,  98],
       [148,  68,  52,   5]])

In [30]:
v1 = np.random.randint(0,81,1)
v2 = np.random.randint(0,81,1)
v3 = np.random.randint(0,81,1)
v4 = np.random.randint(0,81,1)
v5 = np.random.randint(0,81,1)
v6 = np.random.randint(0,81,1)
v7 = np.random.randint(0,81,1)
v8 = np.random.randint(0,81,1)
v9 = np.random.randint(0,81,1)
v10 = np.random.randint(0,81,1)
v11 = np.random.randint(0,81,1)
v12 = np.random.randint(0,81,1)
v13 = np.random.randint(0,81,1)
v14 = np.random.randint(0,81,1)
v15 = np.random.randint(0,81,1)
v16 = np.random.randint(0,81,1)

In [31]:
arr3 = np.array([arr[v1], arr[v2], arr[v3], arr[v4], arr[v5], arr[v6], arr[v7], arr[v8], arr[v9], arr[v10], arr[v11], arr[v12], arr[v13], arr[v14], arr[v15], arr[v16]]).reshape(4,4)
arr3

array([[ 11,  58, 196,  11],
       [ 98,  58, 107,  98],
       [ 37, 133,  98, 123],
       [  2,  58, 178, 107]])

In [32]:
arr4 = arr2 * arr3
arr4

array([[ 1298,  6090, 10976,  1452],
       [  196,  1218, 15836, 14700],
       [ 1776, 11970,  9604, 12054],
       [  296,  3944,  9256,   535]])

In [34]:
arr4[0]

array([ 1298,  6090, 10976,  1452])

In [35]:
arr4[1]

array([  196,  1218, 15836, 14700])

In [36]:
arr4[2]

array([ 1776, 11970,  9604, 12054])

In [37]:
arr4[3]

array([ 296, 3944, 9256,  535])

### SOAL 2

In [40]:
arr5 = np.linspace(0,100,50)
arr5

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [75]:
arr6 = arr5[4:24].reshape(4,5)
arr6

array([[ 8.16326531, 10.20408163, 12.24489796, 14.28571429, 16.32653061],
       [18.36734694, 20.40816327, 22.44897959, 24.48979592, 26.53061224],
       [28.57142857, 30.6122449 , 32.65306122, 34.69387755, 36.73469388],
       [38.7755102 , 40.81632653, 42.85714286, 44.89795918, 46.93877551]])

In [83]:
arr6.reshape(1,20)

array([[ 8.16326531, 10.20408163, 12.24489796, 14.28571429, 16.32653061,
        18.36734694, 20.40816327, 22.44897959, 24.48979592, 26.53061224,
        28.57142857, 30.6122449 , 32.65306122, 34.69387755, 36.73469388,
        38.7755102 , 40.81632653, 42.85714286, 44.89795918, 46.93877551]])

In [78]:
nmax = arr6.max()
nmax

46.93877551020408

In [79]:
arr6.argmax()

19

In [80]:
nmin = arr6.min()
nmin

8.16326530612245

In [81]:
arr6.argmin()

0

In [82]:
nmax + nmin

55.10204081632653

### SOAL 3

In [126]:
parray = 7

arr7 = np.random.randint(0,11,parray)
arr7

array([ 1,  4,  1,  3, 10,  5,  1])

In [127]:
if parray % 2 == 0:
    arr7[(parray//2):] = 22
else:
    arr7[:((parray+1)//2)] = 23

In [132]:
arr7

array([23, 23, 23, 23, 10,  5,  1])

In [129]:
arr7>20

array([ True,  True,  True,  True, False, False, False])

In [130]:
arr7[arr7>20]

array([23, 23, 23, 23])

### SOAL 4

In [204]:
n = int(np.random.randint(1,21,1))
n

12

In [205]:
arr8 = np.zeros(n*4).reshape(4,n)
arr8

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [206]:
n1 = np.random.randint(1,101,4)
n1

array([89, 23, 62, 14])

In [207]:
for i in range(4):
    for j in range(len(n1)):
        arr8[i] = n1[i]

In [208]:
arr8

array([[89., 89., 89., 89., 89., 89., 89., 89., 89., 89., 89., 89.],
       [23., 23., 23., 23., 23., 23., 23., 23., 23., 23., 23., 23.],
       [62., 62., 62., 62., 62., 62., 62., 62., 62., 62., 62., 62.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [213]:
(np.average(arr8[0]) + np.average(arr8[2])) / 2

75.5

### SOAL 5

In [ ]:
print('Menu 1')
print('Menu 2')
print('Menu 3')
print('Menu 4')
pilih = int(input('Pilih menu: '))
if pilih == 1:
    pa = int(input('Masukkan panjang array: '))
    arr9 = np.zeros(pa)
    for i in range(pa):
        data = int(input('Angkat ke-' + str(i+1) + ': '))
        arr9[i] = data
    print(arr9)
    baris = int(input('Baris matriks yang diinginkan: '))
    kolom = int(input('Kolom matriks yang diinginkan: '))
    arr9 = arr9.reshape(baris,kolom)
    print(arr9)
elif pilih == 2:
    li = []
    jumlahdata = 0
    while jumlahdata < 25:
        datrand = abs(np.random.randn()*10)
        if datrand >= 1 and datrand < 10:
            li.append(datrand)
            jumlahdata += 1
    arr10 = np.array(li).reshape(5,5)
    print(arr10)
    nmax = arr10.max()
    print('Nilai maksimum: ' + str(nmax))
    nmin = arr10.min()
    print('Nilai minumum: ' + str(nmin))
    print(np.array([arr10[0]*arr10[3],arr10[2]*3,arr10[4]*2]))
elif pilih == 3:
    arr11 = np.random.randint(1,11,4).reshape(2,2)
    print(arr11)
    arr11 = np.linalg.inv(arr11)
    print(arr11)
elif pilih == 4:
    arr12 = np.random.randint(1,11,9).reshape(3,3)
    print(arr12)
    det = np.linalg.det(arr12)
    print('Nilai determinan: ' + str(det))
else:
    print('Masukkan pilihan yang benar')

In [301]:
# HASIL MENU 1

Menu 1
Menu 2
Menu 3
Menu 4
Pilih menu: 1
Masukkan panjang array: 9
Angkat ke-1: 1
Angkat ke-2: 2
Angkat ke-3: 3
Angkat ke-4: 4
Angkat ke-5: 5
Angkat ke-6: 6
Angkat ke-7: 7
Angkat ke-8: 8
Angkat ke-9: 9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
Baris matriks yang diinginkan: 3
Kolom matriks yang diinginkan: 3
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [302]:
# HASIL MENU 2

Menu 1
Menu 2
Menu 3
Menu 4
Pilih menu: 2
[[9.5854524  7.84671964 1.84528016 8.37987097 1.06587244]
 [2.63929129 4.31730803 6.03173253 5.3516032  2.63730765]
 [8.61371188 1.37408429 3.35072101 1.01925976 5.53315881]
 [3.9494507  1.1810758  1.16849899 7.14653825 4.30658688]
 [9.65167722 7.40652373 4.12795527 1.43669773 3.66328636]]
Nilai maksimum: 9.651677222977357
Nilai minumum: 1.0192597594717392
[[37.85727172  9.26757071  2.156208   59.88706838  4.59027226]
 [25.84113563  4.12225288 10.05216303  3.05777928 16.59947643]
 [19.30335445 14.81304746  8.25591054  2.87339546  7.32657272]]


In [303]:
# HASIL MENU 3

Menu 1
Menu 2
Menu 3
Menu 4
Pilih menu: 3
[[1 5]
 [2 2]]
[[-0.25   0.625]
 [ 0.25  -0.125]]


In [304]:
# HASIL MENU 4

Menu 1
Menu 2
Menu 3
Menu 4
Pilih menu: 4
[[10  2  2]
 [ 6  8 10]
 [ 6  8  7]]
Nilai diskriminan: -204.0000000000001


### SOAL 6

In [307]:
ser1 = pd.Series(np.random.uniform(1,50,10),index=['Apel', 'Jeruk', 'Manggis','Belimbing','Semangka','Pepaya','Pisang','Pir','Melon','Stroberi'])
ser1

Apel          9.587312
Jeruk         1.921830
Manggis      47.577656
Belimbing    25.736344
Semangka     30.768876
Pepaya       31.600232
Pisang       16.153915
Pir          29.660662
Melon        34.915976
Stroberi      3.715269
dtype: float64

In [308]:
ser2 = pd.Series(['Jawa','Bali','Sumatra','Kalimantan','Sulawesi'],index=['Jakarta','Denpasar','Medan','Samarinda','Makassar'])
ser2

Jakarta            Jawa
Denpasar           Bali
Medan           Sumatra
Samarinda    Kalimantan
Makassar       Sulawesi
dtype: object

In [310]:
ser3 = pd.Series(np.random.randint(11,50,10),index=['Apel','Anggur','Aprikot','Alpukat','Ilama','Illawara','Imbe','Mangga','Manggis','Markisa'])
ser3

Apel        33
Anggur      33
Aprikot     47
Alpukat     11
Ilama       16
Illawara    15
Imbe        27
Mangga      42
Manggis     29
Markisa     25
dtype: int64

In [312]:
jumlahan12 = ser1 + ser2
jumlahan12

Apel         NaN
Belimbing    NaN
Denpasar     NaN
Jakarta      NaN
Jeruk        NaN
Makassar     NaN
Manggis      NaN
Medan        NaN
Melon        NaN
Pepaya       NaN
Pir          NaN
Pisang       NaN
Samarinda    NaN
Semangka     NaN
Stroberi     NaN
dtype: object

In [314]:
kali13 = ser1 * ser3
kali13

Alpukat              NaN
Anggur               NaN
Apel          316.381283
Aprikot              NaN
Belimbing            NaN
Ilama                NaN
Illawara             NaN
Imbe                 NaN
Jeruk                NaN
Mangga               NaN
Manggis      1379.752037
Markisa              NaN
Melon                NaN
Pepaya               NaN
Pir                  NaN
Pisang               NaN
Semangka             NaN
Stroberi             NaN
dtype: float64

### SOAL 7

In [404]:
df = pd.DataFrame(index='1 3 5 7 9 11 13 15 17 19'.split(),columns='A B C'.split())
df['A'] = np.random.randint(1,101,10)
df['B'] = np.linspace(1,7,10)
df['C'] = np.random.uniform(1,201,10)
df

A         B           C
1   93  1.000000  170.696625
3   38  1.666667   78.793291
5   10  2.333333  177.710807
7   42  3.000000   76.169552
9   82  3.666667   25.129794
11  14  4.333333  188.490892
13  13  5.000000  103.111684
15  74  5.666667   32.319825
17  44  6.333333   50.470450
19  81  7.000000  188.765636

In [405]:
df['D'] = df['A'] + df['B']
df['E'] = df['B'] * df['C']
df

A         B           C          D            E
1   93  1.000000  170.696625  94.000000   170.696625
3   38  1.666667   78.793291  39.666667   131.322152
5   10  2.333333  177.710807  12.333333   414.658550
7   42  3.000000   76.169552  45.000000   228.508657
9   82  3.666667   25.129794  85.666667    92.142578
11  14  4.333333  188.490892  18.333333   816.793867
13  13  5.000000  103.111684  18.000000   515.558419
15  74  5.666667   32.319825  79.666667   183.145677
17  44  6.333333   50.470450  50.333333   319.646184
19  81  7.000000  188.765636  88.000000  1321.359451

In [406]:
df.drop('B',axis=1,inplace=True)
df

A           C          D            E
1   93  170.696625  94.000000   170.696625
3   38   78.793291  39.666667   131.322152
5   10  177.710807  12.333333   414.658550
7   42   76.169552  45.000000   228.508657
9   82   25.129794  85.666667    92.142578
11  14  188.490892  18.333333   816.793867
13  13  103.111684  18.000000   515.558419
15  74   32.319825  79.666667   183.145677
17  44   50.470450  50.333333   319.646184
19  81  188.765636  88.000000  1321.359451

### SOAL 8

In [413]:
df2 = pd.DataFrame(index='P Q R S T U V W X'.split(),columns='1 2 3 4 5 6'.split())

# KOLOM 1
df2.loc['P','1'] = df.loc['1','A']
df2.loc['Q','1'] = df.loc['5','A']
df2.loc['R','1'] = df.loc['9','A']
df2.loc['S','1'] = df.loc['3','A']
df2.loc['T','1'] = df.loc['7','A']
df2.loc['U','1'] = df.loc['11','A']
df2.loc['V','1'] = df.loc['9','A']
df2.loc['W','1'] = df.loc['11','A']
df2.loc['X','1'] = df.loc['13','A']

# KOLOM 2
df2['2'] = df2['1'] * 3

# KOLOM 3
df2.loc['P','3'] = df.loc['1','E']
df2.loc['Q','3'] = df.loc['3','E']
df2.loc['R','3'] = df.loc['5','E']
df2.loc['S','3'] = df.loc['7','E']
df2.loc['T','3'] = df.loc['1','C']
df2.loc['U','3'] = df.loc['3','C']
df2.loc['V','3'] = df.loc['5','C']
df2.loc['W','3'] = df.loc['7','C']
df2.loc['X','3'] = df.loc['1','A']

# KOLOM 4
df2['4'] = np.zeros(9)

# KOLOM 5
df2['5'] = np.ones(9)

# KOLOM 6
df2['6'] = df2['5'] / df2['3']

df2

1    2        3    4    5           6
P  93  279  170.697  0.0  1.0  0.00585835
Q  10   30  131.322  0.0  1.0  0.00761486
R  82  246  414.659  0.0  1.0  0.00241162
S  38  114  228.509  0.0  1.0   0.0043762
T  42  126  170.697  0.0  1.0  0.00585835
U  14   42  78.7933  0.0  1.0   0.0126914
V  82  246  177.711  0.0  1.0  0.00562712
W  14   42  76.1696  0.0  1.0   0.0131286
X  13   39       93  0.0  1.0   0.0107527

In [412]:
df2[df2>5]

1    2        3   4   5    6
P  93  279  170.697 NaN NaN  NaN
Q  10   30  131.322 NaN NaN  NaN
R  82  246  414.659 NaN NaN  NaN
S  38  114  228.509 NaN NaN  NaN
T  42  126  170.697 NaN NaN  NaN
U  14   42  78.7933 NaN NaN  NaN
V  82  246  177.711 NaN NaN  NaN
W  14   42  76.1696 NaN NaN  NaN
X  13   39       93 NaN NaN  NaN

### SOAL 9

In [42]:
print('Menu 1')
print('Menu 2')
print('Menu 3')
print('Menu 4')
p = int(input('Masukkan pilihan Anda: '))
if p == 1:
    bar = int(input('Masukkan jumlah baris: '))
    kol = int(input('Masukkan jumlah kolom: '))
    df3 = pd.DataFrame(index=range(1,bar+1),columns=range(1,kol+1))
    for i in range(1,kol+1):
        if i % 2 == 0:
            df3[i] = range(12,22)
        else:
            df3[i] = np.random.randint(1,11,10)
    print(df3)
elif p == 2:
    df4 = pd.DataFrame(index=range(1,11),columns=range(1,6))
    jrand = 0
    li1 = []
    while jrand < 10:
        rand = int(np.random.randint(10,51,1))
        if rand % 2 == 0:
            li1.append(rand)
            jrand += 1
    df4[1] = li1
    jrand = 0
    li2 = []
    while jrand < 10:
        rand = int(np.random.randint(10,51,1))
        if rand % 2 == 0:
            li2.append(rand)
            jrand += 1
    df4[2] = li2
    jrand = 0
    li3 = []
    while jrand < 10:
        rand = int(np.random.randint(1,30,1))
        if rand % 2 != 0:
            li3.append(rand)
            jrand += 1
    df4[3] = li3
    jrand = 0
    li4 = []
    while jrand < 10:
        rand = int(np.random.randint(1,30,1))
        if rand % 2 != 0:
            li4.append(rand)
            jrand += 1
    df4[4] = li4
    df4[5] = np.linspace(1,3,10)
    print(df4)
elif p == 3:
    df5 = pd.DataFrame(np.random.randn(10,3),index=range(1,11),columns=range(1,4))
    print(df5[df5>5])
elif p == 4:
    df6 = pd.DataFrame(index=range(1,11),columns=range(1,5))
    # KOLOM 1
    kalimat = input('Masukkan sebuah kalimat: ').replace(' ','')
    pecahan = list(kalimat[0:10:1])
    df6[1] = pecahan
    # KOLOM 2
    fibo = [0, 1]
    for i in range(2,10):
        fibo.append(fibo[i-1]+fibo[i-2])
    df6[2] = fibo
    # KOLOM 3
    df6[3] = np.random.uniform(1,21,10)
    # KOLOM 4
    df6[4] = df6[2] * df6[3]
    print(df6)

Menu 1
Menu 2
Menu 3
Menu 4
Masukkan pilihan Anda: 4
Masukkan sebuah kalimat: saya suka makan roti coklat
    1   2          3           4
1   s   0   1.468456    0.000000
2   a   1  11.071385   11.071385
3   y   1   4.039850    4.039850
4   a   2  16.895088   33.790176
5   s   3   5.792000   17.375999
6   u   5   8.525239   42.626196
7   k   8   4.179140   33.433117
8   a  13  18.107147  235.392913
9   m  21   7.553315  158.619614
10  a  34   3.890351  132.271945
